### ISSUE TITLE
Feature request: derived parameters

### ISSUE THREAD

**Issue by joezuntz** [minaskar/pocomc#1]
Really excited to try out your sampler - I'm writing the CosmoSIS interface now.

One thing that would help would be being able to save derived parameters, so e.g. we can make sigma_8 - Omega_m plots after sampling in A_s without further processing. Not sure how easy that is here - it might clash with your vectorization tests.

**Comment by davidnabergoj** [comment]
Thanks for the request! I agree that this would be useful and we are looking into it.

**Comment by minaskar** [comment]
I'm closing this request as this feature is now included in the >1.1.0 versions

**Comment by joezuntz** [comment]
Cool, thanks!!
