### ISSUE TITLE
Minor naming error in quickstart.ipynb

### ISSUE THREAD

**Issue by marylou-gabrie** [minaskar/pocomc#11]
Two namings are used for `n_particles`/`nparticles`and `n_dim`/`ndim` in `docs/build/jupyter_execute/pages/quickstart.ipynb`.

#openjournals/joss-reviews#4634

**Comment by davidnabergoj** [comment]
Thanks for letting us know! We've fixed this in d3698226e38ad0475314a3dddf9eb4de179f432b and the change is now visible on the [documentation page](https://pocomc.readthedocs.io/en/latest/pages/quickstart.html).
