### ISSUE TITLE
Typo in Readme.md example

### ISSUE THREAD

**Issue by kazewong** [minaskar/pocomc#15]
In Basic example section of the readme, nwalkers is used in generating the prior but it is not defined. Please change it to n_particles.

#https://github.com/openjournals/joss-reviews/issues/4634

**Comment by kazewong** [comment]
In https://pocomc.readthedocs.io/en/latest/advanced.html#parallelisation, after

```
import os

os.environ["OMP_NUM_THREADS"] = "1"
```

I think it should be beginning instead beggining.

**Comment by davidnabergoj** [comment]
Thanks for the issue, we have fixed the readme example in 7b8fec74801fdc2c87175859ebfbd781f40a745a and the typo in 36624396097f8f21f6a35466b7888490fa4ac395.
