### ISSUE TITLE
self.logw infinite

### ISSUE THREAD

**Issue by kmzzhang** [minaskar/pocomc#18]
I'm running an inference where my log_like function could return -np.inf even for parameters within the prior. I'm encountering this error message:

~/anaconda3/envs/python3/lib/python3.8/site-packages/pocomc/sampler.py in _resample(self, u, x, J, L, P)
    615 
    616         assert np.all(~np.isnan(self.logw))
--> 617         assert np.all(np.isfinite(self.logw))
    618         assert np.all(~np.isnan(w))
    619         assert np.all(np.isfinite(w))

AssertionError: 

The progress bar is: Iter: 1it [00:00, 264.16it/s, beta=1.6e-10, calls=768, ESS=0.949, logZ=-.0674, accept=0.234, N=0, scale=1]

I read the code and my impression is that is error message is entirely expected? First, self.L is initiated as -np.inf where only the in-prior samples are replaced by the likelihood:
            self.L = np.full((len(self.x),), -np.inf)
            self.L[finite_prior_mask] = self._log_like(self.x[finite_prior_mask])

And later self.logw is calculated as
            self.logw = logw_prev + self.L * (beta - beta_prev)

Maybe pocomc requires log_like to be finite when log_prior is finite?

**Comment by minaskar** [comment]
I'm closing this as this is already resolved in the later versions.

**Comment by Andrew-Swan** [comment]
This still seems to be an issue in the current version of the code on the main branch.

Modifying the likelihood in the (github) quickstart example to return some -np.inf values causes a crash within a few iterations:

import pocomc as pc
import numpy as np
from scipy.stats import uniform

n_dim = 10  # Number of dimensions

prior = pc.Prior(n_dim*[uniform(-10.0, 20.0)]) # U(-10,10)

def log_likelihood(x):
    likelihood = -np.sum(10.0*(x[:,::2]**2.0 - x[:,1::2])**2.0 + (x[:,::2] - 1.0)**2.0, axis=1)
    return np.where(x[:,0] < 5, likelihood, -np.inf)

sampler = pc.Sampler(
    prior=prior,
    likelihood=log_likelihood,
    vectorize=True,
)
sampler.run()

**Comment by minaskar** [comment]
This should now be fixed in version 1.2.1. 

Let me know if there're still issues.

**Comment by Andrew-Swan** [comment]
Amazing, thank you. I tried out the new version and it's looking good so far.

**Comment by minaskar** [comment]
Thanks! Any further comments are welcome.

I'm closing this for now but feel free to open a new issue if you have new suggestions, requests, bugs, etc.
