### ISSUE TITLE
Feature request: backups/restarts

### ISSUE THREAD

**Issue by ajdittmann** [minaskar/pocomc#2]
Being able to restart jobs which terminate prematurely would be extremely useful for challenging analyses, especially on HPC clusters which impose maximum time limits.
To be generally useful, restarting should work regardless of what sort of pool was used (number of cores, MPI vs. multiprocessing, etc.).

**Comment by minaskar** [comment]
Hi @ajdittmann,

The latest version of `pocoMC` supports state saving and loading. Have a look here https://pocomc.readthedocs.io/en/latest/advanced.html#saving-and-resuming-runs for some instructions on how to use it.

Let me know if there's anything else that might be useful.
