### ISSUE TITLE
Potential issue in `pocomc.flow`

### ISSUE THREAD

**Issue by francois-rozet** [minaskar/pocomc#38]
Hello @minaskar, thanks for using Zuko in pocoMC! I hope you like it ;)

I quickly checked how you were using it, and noticed a potential issue with the following.

https://github.com/minaskar/pocomc/blob/61d7e0f592d5828bed2d05306bf908ace9856da1/pocomc/flow.py#L55

Here, `self.transform` is a `torch.distributions.Transform` created with the current weights of `self.flow`. This means that updating the parameters of the flow (`self.flow`) may not affect `self.transform`. Instead, it would be safer to make `self.transform` a property that returns `self.flow().transform` without storing it, such that they are always tied.

```python
@property
def transform(self):
    return self.flow().transform
```

or, equivalently,

```python
@property
def transform(self):
    return self.flow.transform()
```

In addition, here,

https://github.com/minaskar/pocomc/blob/61d7e0f592d5828bed2d05306bf908ace9856da1/pocomc/flow.py#L89-L91

you can use the `call_and_ladj` method on the reverse transformation.

```python
x, logdetj = self.transform.inv.call_and_ladj(u)
```

And, here,

https://github.com/minaskar/pocomc/blob/61d7e0f592d5828bed2d05306bf908ace9856da1/pocomc/flow.py#L121-L123

you can use the `rsample_and_log_prob` method of the flow, which is faster than inv + log_prob.

```python
x, log_p = self.flow().rsample_and_log_prob((size,))
```

Tell me if you have any issues.

**Comment by minaskar** [comment]
Thanks for the suggestions @francois-rozet !
