### ISSUE TITLE
Feature Request: continue sampling after completion

### ISSUE THREAD

**Issue by ajdittmann** [minaskar/pocomc#44]
I think it would be useful to be able to continue a run after its initial completion.

For example, let's say you were to carry out a couple runs at different resolutions to check for convergence, using the default ``n_total`` and ``n_evidence`` values. Then, once you are convinced you have a sufficiently rigorous analysis, it would be nice to continue one of the previous runs by setting ``n_total`` to a larger value. 
This would be nice for drawing a bunch of samples from the posterior, without going through all of the beta < 1 sampling again. Would that cause any problems I have not foreseen?

It seems like it might be possible to implement this sort of thing by moving ``self.n_total = int(n_total)`` out of the ``else`` block around line 389 in sampler.py, but I have not looked into how this would interact with the progress bar.  

A related, minor suggestion is that it might be convenient to automatically save a checkpoint upon completion when ``output_dir`` is not ``None``.

**Comment by minaskar** [comment]
Thanks for the suggestion. This feature is now included in version 1.2.0, just released. 

In particular, when ``save_every``  is not ``None``, ``pocoMC`` will save a final state file by default when sampling completes. You should be able to load that state and add more samples by increasing ``n_total`` and ``n_evidence``.

Furthermore, you can also now continue runs without saving states. Simply call ``run`` again with updated ``n_total`` and ``n_evidence`` values.

Let me know if that's useful for your analyses.

**Comment by ajdittmann** [comment]
Thanks, I've confirmed locally that this works, and look forward to using it in my production analyses.
